### ISSUE TITLE
Internal Server issue after upgrading thruk from version  2.20-2  to v2.24-2  (#883)

### ISSUE THREAD

**Issue by czzarfrag** [sni/Thruk#886] opened 2018-11-23 09:49 UTC
**Describe the bug**
Please report this issue by mail to: bugs@thruk.org

Please describe what you did:
Make sure the report does not contain confidential information.
---------------
Url:        status.cgi?host=all&view_mode=xls
Browser:    
Version:    2.24-2
Release:    November 06, 2018
LMD:        lmd - version 1.3.6 (Build: )
Backends:   State / Program Version / Data Source Version
0 / 4.3.4 / 1.2.8p27
2 /  / 
0 / 4.3.4 / 1.2.6p15
uname:      Linux dkrdswppthrukt01.vestasext.net 2.6.32-754.6.3.el6.x86_64 #1 SMP Tue Sep 18 10:29:08 EDT 2018 x86_64
release:    Red Hat Enterprise Linux Server release 6.10 (Santiago)
Stacktrace:
internal lmd error - /var/cache/thruk/lmd/live.sock: socket error - Post http://172.26.66.71:8080/query: EOF
at /usr/share/thruk/lib/Monitoring/Livestatus/Class/Lite.pm line 386
at /usr/share/thruk/lib/Thruk.pm line 350
Thruk::_dispatcher('HASH(0x307c8c8)') called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
eval {...} called at /usr/lib64/thruk/perl5/Plack/Util.pm line 145
Plack::Util::run_app('CODE(0x2fdb2a0)', 'HASH(0x307c8c8)') called at /usr/lib64/thruk/perl5/Plack/Handler/FCGI.pm line 145
Plack::Handler::FCGI::run('Plack::Handler::FCGI=HASH(0x25b0d48)', 'CODE(0x2fdb2a0)') called at /usr/share/thruk/script/thruk_fastcgi.pl line 24

**Thruk Version**
2.24-2

![thruk error](https://user-images.githubusercontent.com/23075113/48937097-07106980-ef48-11e8-9eab-027baf32c816.png)

*

**Comment by sni** [comment] 2018-11-23 09:51
duplicate of #885 
you guys obviously work for the same company, please talk to each other befor opening issues

**Closed by sni** 2018-11-23 09:51 UTC

**Comment by Delat0918** [comment] 2018-11-26 07:50
Hi Sven.

This is another issue which is the  export of customvariables to excel , we did upgrade from 2.20 to 2.22 however when we run it again the output data for Duration does not exist. Hoping for your kind advice on this.

Regards,
Dennis
