### ISSUE TITLE
Business Process - Unable to show the state

### ISSUE THREAD

**Issue by dcop7** [sni/Thruk#681] opened 2017-02-09 17:21 UTC
Hi,

When using Host/Service Status in Business Process, specifying a service, the state is always UNKNOWN, but opening the service, it has the state OK.

If I don't specify any service, indicating only the Host, it read the status correctly.

Regards,
Diogo

**Comment by dcop7** [comment] 2017-02-09 17:38
![print](https://cloud.githubusercontent.com/assets/2600148/22795368/601b7274-eeee-11e6-8155-8d371691a4f3.png)

This is a print screen. I've marked the host with GREEN and the service with RED. As you can see, the service is "OK", in the dashboard, the color is purple, which is the state "UNKNOWN".

I'm on the last version (2.12-3).

**Comment by sni** [comment] 2017-02-15 16:35
Cannot reproduce that, can you create a bp on demo.thruk.org which shows this problem?

**Comment by dcop7** [comment] 2017-02-16 11:24
In the demo, I can't reproduce it. It should be a problem in our side. Thank you.

**Comment by dcop7** [comment] 2017-02-16 11:29
I've noticed something. It could be because the service name was special characters? My service is: APP_V_U-P[C-D:No]_Total-Number

**Comment by sni** [comment] 2017-02-16 11:31
thats probably the reason, thruk thinks this is a regular expression and it doesn't match any service

**Comment by dcop7** [comment] 2017-02-16 11:32
If I choose a service without "[" and "]", it works.

**Comment by dcop7** [comment] 2017-02-16 11:34
ok,thank you

**Comment by dcop7** [comment] 2017-02-16 11:40
There isn't any way around for this to work with "[" on the services? We have many services with "[".

**Comment by sni** [comment] 2017-02-16 11:42
have you tried to escape the brackets, like \[\]. Then its at least a valid regular expression which should match a service.

**Comment by dcop7** [comment] 2017-02-16 11:53
It worked with "\". You can close the issue. Thanks

**Comment by sni** [comment] 2017-02-20 22:49
Thats fixed with the latest nightlys already.

**Closed** 2017-03-09 20:14 UTC
