### ISSUE TITLE
Configuration does not show all items for hosts/services

### ISSUE THREAD

**Issue by gitmopp** [sni/Thruk#752] opened 2017-09-06 08:10 UTC
I' m using the cache thrug_logs and I can see the host entries in the tables *_host.
But If I open the URL /thruk/#cgi-bin/config.cgi?type=hosts# or /thruk/#cgi-bin/config.cgi?type=services# only 100 entries are shown: "100 of 100 Matching Entries Displayed".
This problem applies for hosts and services. All other lists like Contacts, Timeperiods, Contact Groups ... are showing more than 100 entries.

**Comment by gitmopp** [comment] 2017-12-18 12:52
Can you help me to debug the problem?
I' m using lmd, is it a query against the database or a livequery using livestatus?
How can I view which query is executed?

**Comment by gitmopp** [comment] 2017-12-19 13:23
If I set `use_pager = 0` to all entries are displayed.
If I enable the pager and set it to 400 only the first 400 matches are displayed.
```
use_pager     = 1
paging_steps  = *400, 500, 1000, 5000, all
```
The problem is only in the config.cgi.

**Comment by gitmopp** [comment] 2017-12-21 10:57
One more thing I have to add. All hosts or services are shown in all other views like /thruk/#cgi-bin/status.cgi?hostgroup=all&style=hostdetail . The problem exists only in  /thruk/#cgi-bin/config.cgi?type=hosts#
And only with use_pager = 1. So it is not a problem with the query or the data. It seems like the pager does not work in this view.

**Comment by sni** [comment] 2017-12-21 18:12
Is this the latest icinga 2 release? If so, you should open a ticket there. This most likely a problem in the icinga2 livestatus implementation.

**Comment by gitmopp** [comment] 2017-12-21 19:01
The backend is Nagios with livestatus and lmd.
I tried my best to debug the code, but it was not possible for me to find the problem. On a test system without lmd and Nagios it works fine, so I guess it is related to the lmd_optimizations.

These are my latest findings.
Thruk/Backend/Manager.pm (sub _page_data)
$totalsize and scalar @{$data} both have the value of 100 for hosts and services. For other objecty like contact the real number is shown like 166.
If I open the URL /thruk/cgi-bin/config.cgi?type=hosts&entries=all I see all hosts and $totalsize and scalar @{$data} have the correct value.

Thruk/Backend/Provider/Livestatus.pm (sub get_contacts)
```$self->_get_table('contacts', \%options);```
returns all contacts (not only the first 100), the parameter $options{'options'}->{'limit'} is not set.

In sub get_hosts the $options{'options'}->{'limit'} is set, it is set through sub _optimized_for_wrapped_json
```
          'options' => {
                         'limit' => 100,
                         'offset' => 0,
                         'sort' => [
                                     'name asc'
                                   ],
                         'wrapped_json' => 1
                       },
          'pager' => {
                       'entries' => 100,
                       'first' => undef,
                       'last' => undef,
                       'next' => undef,
                       'page' => 1,
                       'pages' => '',
                       'previous' => undef
                     },
```

When I set limit to undef it will load all data in one page and will show the pager icon.

I already tried some code changes, but without any luck.

**Comment by sni** [comment] 2017-12-21 19:20
Have you tried updating LMD? I cannot reproduce this here.

**Comment by gitmopp** [comment] 2017-12-21 19:23
I already updated to 1.1.5.
I' ll clear the database and let lmd fetch the data again and will post a comment about the result.

**Comment by gitmopp** [comment] 2017-12-21 23:13
I deactivated the logcache and `use_lmd_core=0` and everything works fine.
Re-enabled the logcache and it still works, so no problem with the logcache database.
Re-enabled LMD and it stops working.
So the problem is related to LMD.

Test of LMD is okay.
```
echo -e 'GET hosts\n' | unixcat /var/cache/thruk/lmd/live.sock | wc -l
5029
echo -e 'GET hosts\nOffset: 100\nLimit: 10\n' | unixcat /var/cache/thruk/lmd/live.sock | wc -l
13
```
Did you have connected LMD to multiple backends in your test?
What else can I try to identify the problem?

**Comment by gitmopp** [comment] 2017-12-22 09:07
@sni Can you try the following to reproduce the problem?
Install omd-2.60-labs-edition-sles12sp2.x86_64.rpm

```
# omd create thruklmd
# su - thruklmd
$ vi ~/etc/thruk/thruk_local.d/lmd.cfg
use_lmd_core=1
lmd_core_bin=~/bin/lmd
lmd_core_config=~/etc/thruk/lmd.ini

$ omd restart apache
$ omd start
$ for ((i=1;i<600;i++)); do echo -e "define host {\nhost_name host_$i\naddress 127.0.0.1\nuse generic-host\n}\n"; done >> ~/etc/naemon/conf.d/hosts.cfg
$ omd reload naemon
```
And open https://127.0.0.1/thruklmd/thruk/#cgi-bin/config.cgi?type=hosts#

You will see 100 hosts instead of 599 hosts.


I did a trace on lmd:
```
GET hosts
Backends: 31f62
Columns: accept_passive_checks acknowledged action_url action_url_expanded active_checks_enabled address alias check_command check_freshness check_interval check_options check_period check_type checks_enabled childs comments current_attempt current_notification_number event_handler event_handler_enabled execution_time custom_variable_names custom_variable_values first_notification_delay flap_detection_enabled groups has_been_checked high_flap_threshold icon_image icon_image_alt icon_image_expanded is_executing is_flapping last_check last_notification last_state_change latency low_flap_threshold max_check_attempts name next_check notes notes_expanded notes_url notes_url_expanded notification_interval notification_period notifications_enabled num_services_crit num_services_ok num_services_pending num_services_unknown num_services_warn num_services obsess_over_host parents percent_state_change perf_data plugin_output process_performance_data retry_interval scheduled_downtime_depth state state_type modified_attributes_list last_time_down last_time_unreachable last_time_up display_name in_check_period in_notification_period contacts contact_groups last_state_change_order peer_key
Limit: 100
Offset: 0
Sort: name asc
OutputFormat: wrapped_json
ResponseHeader: fixed16
```
The query is okay and works.
wrapped_json, limit and offset are used for hosts and services. All other queries do not use it, e. g.
```
GET contacts
Backends: 31f62
Columns: name alias email pager service_notification_period host_notification_period peer_key
OutputFormat: json
ResponseHeader: fixed16
```
And all other queries are working fine. Something with the lmd_optimizations seems not to work.

**Comment by sni** [comment] 2017-12-22 10:44
Sorry, i didn't see you were talking about the config page. Should be fixed now.

**Closed** 2017-12-22 10:43 UTC

**Comment by gitmopp** [comment] 2017-12-22 10:48
Thank you very much, it works!
