### ISSUE TITLE
Debian repos have incorrect libthruk file

### ISSUE THREAD

**Issue by mldailey** [sni/Thruk#1356] opened 2024-04-16 20:22 UTC
**Describe the bug**
Debian systems are unable to install the libthruk package from the opensuse.org repos because the file does not match the size and hashes in the "Packages" file.

**Thruk Version**
libthruk 3.00-1

**To Reproduce**
1. curl -s -o /etc/apt/trusted.gpg.d/naemon.asc "https://build.opensuse.org/projects/home:naemon/signing_keys/download?kind=gpg"
2. echo "deb [signed-by=/etc/apt/trusted.gpg.d/naemon.asc] http://download.opensuse.org/repositories/home:/naemon/Debian_$(lsb_release -rs)/ ./" >> /etc/apt/sources.list.d/naemon-stable.list
3. apt update
4. apt install libthruk
5. Error:
```
Get:25 http://provo-mirror.opensuse.org/repositories/home%3A/naemon/Debian_11 ./ libthruk 3.00-1 [2698 kB]
Err:25 http://provo-mirror.opensuse.org/repositories/home%3A/naemon/Debian_11 ./ libthruk 3.00-1
  File has unexpected size (2700316 != 2698296). Mirror sync in progress? [IP: 91.193.113.70 80]
  Hashes of expected file:
   - SHA256:e49224530b7d30e1313ec853a2a3e211b1a3337d888968bd5f858c270d1c218a
   - SHA1:cf95dce08b03419e46252b7511ccadac4cd9f75a [weak]
   - MD5Sum:45a1ec430694ed44497a13fadebdae44 [weak]
   - Filesize:2698296 [weak]
Fetched 5094 kB in 1s (8605 kB/s)
E: Failed to fetch http://provo-mirror.opensuse.org/repositories/home%3A/naemon/Debian_11/amd64/libthruk_3.00-1_amd64.deb  File has unexpected size (2700316 != 2698296). Mirror sync in progress? [IP: 91.193.113.70 80]
   Hashes of expected file:
    - SHA256:e49224530b7d30e1313ec853a2a3e211b1a3337d888968bd5f858c270d1c218a
    - SHA1:cf95dce08b03419e46252b7511ccadac4cd9f75a [weak]
    - MD5Sum:45a1ec430694ed44497a13fadebdae44 [weak]
    - Filesize:2698296 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Expected behavior**
The package should install normally.

**Additional context**
The same behavior happens in both Debian 11 and Debian 12 (haven't tested any other versions). I have downloaded the file manually and it is indeed the wrong size:
```
wget http://provo-mirror.opensuse.org/repositories/home%3A/naemon/Debian_11/amd64/libthruk_3.00-1_amd64.deb
ls -l libthruk_3.00-1_amd64.deb
-rw-r--r-- 1 root root 2700316 Apr 29  2023 libthruk_3.00-1_amd64.deb
```

Oddly, this date is different from what is shown at [https://download.opensuse.org/repositories/home:/naemon/Debian_11/amd64/](url) in a browser - this shows a date of 10 Feb 2024, rather than 29 Apr 2023.

**Comment by sni** [comment] 2024-04-17 06:15
thanks for bringing this to my attention, i'll gonna have a look.

**Comment by sni** [comment] 2024-04-19 19:53
i cannot reproduce this, i rsynced all files from:
`rsync -av rsync.opensuse.org::buildservice-repos/home:/naemon/.`
Then looking in the debian11 folder:
`-rw-r--r-- 1 user group 2698296 Feb 10 19:46 Debian_11/amd64/libthruk_3.00-1_amd64.deb`
The size is exactly as it should be. Is there some proxy or so in between in your setup?

the hashsum also matches the expected one:

```bash
%> sha256sum Debian_11/amd64/libthruk_3.00-1_amd64.deb
e49224530b7d30e1313ec853a2a3e211b1a3337d888968bd5f858c270d1c218a  Debian_11/amd64/libthruk_3.00-1_amd64.deb
```

**Comment by sni** [comment] 2024-04-19 20:00
but indeed, there seems to be a different or old file here: http://provo-mirror.opensuse.org/repositories/home:/naemon/Debian_11/amd64/
I pushed the latest tag couple of minutes ago, maybe this refreshes those mirrors... There should be a version 3.14 of libthruk there soon.

**Comment by sni** [comment] 2024-04-20 09:04
i am closing this issue, there seems to be a problem with that specific mirror:
https://download.opensuse.org/app/server/provo-mirror.opensuse.org
I suggest using a different mirror.

**Closed by sni** 2024-04-20 09:05 UTC
