### ISSUE TITLE
Debug time bar - start showing after update

### ISSUE THREAD

**Issue by Rohlik** [sni/Thruk#960] opened 2019-07-24 12:33 UTC
Hello,

Can you tell me how I can turn off this debug time bar?
![image](https://user-images.githubusercontent.com/2051154/61793538-a7909380-ae1f-11e9-8b6d-63cc9decaa1b.png)
I update Thruk from 2.14 to 2.30 and this bar start showing and I am not able to find settings for this.

Thank you.

**Comment by sni** [comment] 2019-07-24 12:35
it will show up if you enabled it in your user profile (top right, settings button) or if THRUK_PERFORMANCE_DEBUG=1 environment is set.
It should not show up otherwise.

**Comment by Rohlik** [comment] 2019-07-24 12:46
Thank you for fast answer, but sadly I was not able to find relevant settings.
I can see this on my `User Profile` settings:
![image](https://user-images.githubusercontent.com/2051154/61794449-85981080-ae21-11e9-95a2-df31aadde731.png)

My Linux system does not have `THRUK_PERFORMANCE_DEBUG` env set.

**Comment by sni** [comment] 2019-07-24 12:49
yes, its `Debug Profiles`, but its off already. I will have a look.

**Comment by Rohlik** [comment] 2019-07-25 05:52
Maybe this help:
First, I updated my dev server - Thruk 2.14 ->  2.26 -> 2.30. This dev server is without problem - no debug time bar.
Production server have also Thruk 2.30, but was updated straight from 2.14. Sadly, this production server show debug time bar even it should not.

**Comment by sni** [comment] 2019-07-25 07:35
is that only your account or others as well? Have you tried enabling the Debug Profiles and disabling them again?

**Comment by Rohlik** [comment] 2019-07-25 07:55
I tried more accounts with same results. I also tried Incognito tab in my Chrome browser and turn off the debug features in user's settings but without success.

**Comment by sni** [comment] 2019-07-30 11:53
You could try the nightly to see if the problem is resolved.

**Comment by Rohlik** [comment] 2019-08-06 06:32
I give a shot, but after my holiday.

**Comment by Rohlik** [comment] 2019-09-17 15:23
Hello and sorry for my late update.
I don't know how it is possible, but suddenly everything work as expected = without debug bar.
I did not update Thruk or changed any settings. So it is weird..

**Comment by sni** [comment] 2019-09-17 16:29
great, i will close this then.

**Closed by sni** 2019-09-17 16:29 UTC
