### ISSUE TITLE
Truncated servicedependency when using hostgroups

### ISSUE THREAD

**Issue by riton** [sni/Thruk#930] opened 2019-04-09 07:48 UTC
**Describe the bug**
This bug report follows a discussion initiated on IRC `#naemon` with @sni .
I've created [this repository](https://github.com/riton/naemon_servicedependencies_irc) to hold the full configuration used to reproduce the bug. The _infrastructure_ as been created only for this bug report.

To make it quick, with the following configuration:

```
define servicedependency {
    hostgroup_name                      httpd_worker,httpd_proxy
    service_description                 check httpd proc
    dependent_host_name                 http-client
    dependent_service_description       check get http app health,check get http app statistics
    execution_failure_criteria          w,u,c
    notification_failure_criteria       w,u,c
}
```

Only one host dependency (one from the _httpd_worker_ hostgroup) shows up in Livestatus or Thruk when _3 hosts_ should be expanded from the hostgroups _httpd_worker_ and _httpd_proxy_.

**Thruk Version**
```
[root@b878445f165c /]# rpm -qa '*naemon*'
naemon-1.0.10-0.noarch
naemon-livestatus-1.0.10-0.x86_64
naemon-thruk-1.0.10-0.noarch
libnaemon-1.0.10-0.x86_64
naemon-core-1.0.10-0.x86_64
[root@b878445f165c /]# rpm -qa '*thruk*'
thruk-base-2.28-1.x86_64
thruk-2.28-1.x86_64
libthruk-2.26-0.x86_64
thruk-plugin-reporting-2.28-1.x86_64
naemon-thruk-1.0.10-0.noarch
```

**To Reproduce**
1. Run naemon with [this objects definition file](https://raw.githubusercontent.com/riton/naemon_servicedependencies_irc/master/custom.cfg)
2. Go to the `check get http app health` service
3. See that the `Depends On` list is not complete (according to my understanding)

**Expected behavior**
From my understanding of the `servicedependency` object and the documentation, I'm expecting to see the following list in the `Depends On` display:
* `http-server-1 - check httpd proc`
* `http-server-2 - check httpd proc`
* `http-proxy - check httpd proc`

**Screenshots**
![infrastructure](https://user-images.githubusercontent.com/553730/55782323-51842400-5aac-11e9-9244-8925b032ec5c.png)

![check_get_http_app_health_service_dep](https://user-images.githubusercontent.com/553730/55782331-55b04180-5aac-11e9-93f5-0f49f6b485ee.png)

**Additional context**
Livestatus reports the same _truncated_ informations:

```
[root@b878445f165c /]# echo -e "GET services\nFilter: description = check get http app health\nColumns: depends_exec, depends_notify\n" | unixcat /var/cache/naemon/live
;http-server-2|check httpd proc
```

**Comment by sni** [comment] 2019-05-06 11:12
i am able to reproduce that. But as you already noticed, this seems to be a naemon issue. Could you create/move the issue to naemon/naemon-core please?

**Comment by sni** [comment] 2019-05-08 14:39
since i was working on dependencies anyway,
should be fixed with: https://github.com/naemon/naemon-core/pull/294

**Closed by sni** 2019-05-08 14:39 UTC
