### ISSUE TITLE
BP: problem with children and two parents

### ISSUE THREAD

**Issue by mcasviper** [sni/Thruk#840] opened 2018-07-04 06:26 UTC
I have a node which is a children for two other nodes (worst of). In testmode only one parent (alphabetical first) gets the correct status. It looks like the other never gets a status from the child.

**Thruk Version**
Version 2.20-2
OMD 2.70-labs-edition

**To Reproduce**
1. Create a new Business Process
2. add two "worst of" Nodes
3. add a dummy node to every "worst of" node with state "OK"
4. add a dummy node "child" to one "worst of" node 
5. click edit node on the second "worst of" node
6. go to children
7. add child to this node
8. use testmode or change the status of child to critical
9. only one "worst of" node gets the new state

**Expected behavior**
Both parent nodes get critical if the child gets critical and not just one.

**Screenshots**
![business process_demo_2_parents](https://user-images.githubusercontent.com/5758581/42259810-4e8184bc-7f62-11e8-8868-e008b65498bc.png)

**Desktop (please complete the following information):**
 - Chrome
 - 67

**Additional context**
I paste my demo BP for better understanding:
`{
   "filter" : [],
   "name" : "Demo-2-parents",
   "nodes" : [
      {
         "contactgroups" : [],
         "contacts" : [],
         "create_obj" : 1,
         "depends" : [
            "node2",
            "node3"
         ],
         "filter" : [],
         "function" : "worst()",
         "id" : "node1",
         "label" : "Demo-2-parents"
      },
      {
         "contactgroups" : [],
         "contacts" : [],
         "depends" : [
            "node4",
            "node6"
         ],
         "filter" : [],
         "function" : "worst()",
         "id" : "node2",
         "label" : "anode"
      },
      {
         "contactgroups" : [],
         "contacts" : [],
         "depends" : [
            "node5",
            "node6"
         ],
         "filter" : [],
         "function" : "worst()",
         "id" : "node3",
         "label" : "bnode"
      },
      {
         "contactgroups" : [],
         "contacts" : [],
         "depends" : [],
         "filter" : [],
         "function" : "fixed('OK', '')",
         "id" : "node4",
         "label" : "dummya"
      },
      {
         "contactgroups" : [],
         "contacts" : [],
         "depends" : [],
         "filter" : [],
         "function" : "fixed('OK', '')",
         "id" : "node5",
         "label" : "dummyb"
      },
      {
         "contactgroups" : [],
         "contacts" : [],
         "depends" : [],
         "filter" : [],
         "function" : "fixed('OK', '')",
         "id" : "node6",
         "label" : "child"
      }
   ],
   "rankDir" : "TB",
   "state_type" : "both",
   "template" : ""
}`

**Comment by sni** [comment] 2018-10-22 18:55
i cannot reproduce that behaviour with the current nightly, so i assume this has been fixed already. Please reopen the issue if this still happens with the 2.24 release (which will be released soon) or please try the latest nightly build.

**Closed by sni** 2018-10-22 18:55 UTC
