### ISSUE TITLE
Session files not cleared - inodes full.

### ISSUE THREAD

**Issue by Beatlor** [sni/Thruk#1009] opened 2020-04-06 06:44 UTC
The same bug reportet here: https://github.com/ConSol/omd/issues/88

Same issue in "OMD - Open Monitoring Distribution Version 3.20-labs-edition" version. Today inodes full with 3.8 million SHA-256 session files. System stopped - of course over the weekend.

Helpfull commands:
 find /opt/omd/sites/YOURSITE/var/thruk/sessions/ -xdev -printf '%h\n' | sort | uniq -c | sort -k 1
 find . -type f -mtime +3 -delete

**Comment by sni** [comment] 2020-04-07 09:47
Should be fixed already in the latest Thruk release and in the current OMD nightlys.
Thanks for sharing your commands to cleanup.

**Closed** 2020-04-07 09:46 UTC

**Comment by malcombecerra** [comment] 2020-09-11 20:06
hi sni, can u give in which version or part of code where is fixed?, cuz i cant update to the lastest version , i have 2.32

**Comment by sni** [comment] 2020-09-12 15:53
i don't know which commit exactly fixed it. Have you tried the latest release?

**Comment by Beatlor** [comment] 2020-09-13 10:16
Just want to add the root cause of my issue was an excessive use of Smashing/Dashing from me and my colleagues. My Smashing is using the Thruk API and this caused so many session files.

**Comment by malcombecerra** [comment] 2020-09-14 14:57
@sni i cant try the latest release.. i upgrade to 2.32 a few weeks ago.
@Beatlor maybe its my root cause too, cuz i have some services which consumes the thruk api, and that dir was over 2.2 GB of space and more tan 500KB of inodes occupied. maybe i have to decrese the time of the living session

**Comment by sni** [comment] 2020-09-14 17:49
well, if you cannot upgrade, then the workaround from https://github.com/sni/Thruk/issues/1009#issue-594846464 might help to manually remove old sessions.

**Comment by Beatlor** [comment] 2020-09-14 18:03
I'd created a cron job for removing older session files inside of the OMD site. Since this time no more issues.

**Comment by MP-ICT-Diensten** [comment] 2024-12-24 16:15
Issue exist in OMD 5.41 as well, old sessions are not deleted it seems. Thruk v3.19.20240923 (7ef2135d5)

**Comment by sni** [comment] 2024-12-26 12:40
are you doing a lot of automation? What kind of sessions are those?

**Comment by MP-ICT-Diensten** [comment] 2025-04-17 12:49
We do have automation, currently 52 sessions some go back 3 days (today is April 17)

It seems that a dockerized application using an api connection to thruk is the guilty one I now recognize.  Will make a story here to look into it.  

![Image](https://github.com/user-attachments/assets/85bcc346-352b-4682-a541-79656f6b30d6)
