### ISSUE TITLE
"Service Status Type" and "Service Properties" should not appear in the hosts filter

### ISSUE THREAD

**Issue by eduault** [sni/Thruk#865] opened 2018-10-12 15:52 UTC
**Describe the bug**
When I use an "and" filter for the Hosts widget of a panorama/dashboard, "Service Status Type" and "Service Properties" are proposed in the right part of the filter. 

**Thruk Version**
Thruk Monitoring Webinterface
Version 2.12-3
December 20, 2016

**To Reproduce**
1. Create a panorama/dashboard
2. Edit the panorama
3. Add a Hosts widget (right click > New > Hosts)
4. Edit the Hosts widget
5. Click on "Change filter"
6. Click on "and"

**Expected behavior**
The "Service Status Type" and "Service Properties" should not appear in the hosts filter. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29234693/46879410-4c6c5200-ce46-11e8-8b20-2b10b944339a.png)

**Desktop (please complete the following information):**
 - Browser : Firefox
 - Version : 61.0 (64 bits)

**Comment by sni** [comment] 2018-10-12 19:41
This should be fixed meanwhile. I cannot reproduce that with the latest version.

**Closed by sni** 2018-10-12 19:41 UTC
